# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/STUDY/CPU/pipeline/pipeline.srcs/sources_1/ip/data_mem/data_mem.xci
# IP: The module: 'data_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/STUDY/CPU/pipeline/pipeline.srcs/sources_1/ip/data_mem/data_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_mem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/STUDY/CPU/pipeline/pipeline.srcs/sources_1/ip/data_mem/data_mem.xci
# IP: The module: 'data_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/STUDY/CPU/pipeline/pipeline.srcs/sources_1/ip/data_mem/data_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
